name = "do-multitenant-prompt-manager-api-production"
main = "worker/src/index.ts"
compatibility_date = "2024-10-10"
compatibility_flags = ["nodejs_compat"]

# Environment-specific configuration
[env.production]
name = "do-multitenant-prompt-manager-api-production"

# Production D1 Database
[[env.production.d1_databases]]
binding = "DB"
database_name = "do-multitenant-prompt-manager-production"
database_id = "47e6b3e5-e736-4e9b-b195-b82fa70b6f52"
migrations_dir = "worker/migrations"

# Production KV Namespace
[[env.production.kv_namespaces]]
binding = "PROMPT_CACHE"
id = "31752b95b8c0430598fa265d83877579"