name = "do-multitenant-prompt-manager-api"
main = "worker/src/index.ts"
compatibility_date = "2024-10-10"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "do_multitenant_prompt_manager"
database_id = "b1f2bb31-4bb2-4f25-9b5a-9523be8c62fe"
migrations_dir = "worker/migrations"

[[kv_namespaces]]
binding = "PROMPT_CACHE"
id = "2aa521329da2494eafe5cd08b866281d"

# Development environment variables
[vars]
ALLOWED_ORIGINS = "http://localhost:5173,http://localhost:4173"
